name: Build LaTeX Document
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build-latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move chapter files
        run: |
          mkdir -p ignored
          mv chapters/* ignored/
          cp ignored/* chapters/

      - name: Compile LaTeX document
        uses: DanySK/compile-and-publish-all-latex@2.0.43
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore chapter files
        if: always()
        run: |
          mv ignored/* chapters/
          rm -rf ignored